# Generated by Django 4.2.4 on 2023-08-18 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('year_published', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
