# Generated by Django 4.2.4 on 2023-08-22 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_loan_book_alter_loan_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_id',
            new_name='id',
        ),
    ]
