# Generated by Django 4.2.4 on 2023-08-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_customer_id_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='id',
            new_name='customer_id',
        ),
    ]
