# Generated by Django 4.2.4 on 2023-08-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_id_customer_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='_id',
            new_name='book_id',
        ),
    ]
