# Generated by Django 4.2.4 on 2023-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename__id_book_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loandate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='returndate',
            field=models.DateField(),
        ),
    ]
